name: ETL Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  extract-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: show python version
        run: python --version

  transform-job:
    runs-on: ubuntu-latest
    needs: extract-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run transform.py
        run: python transform.py

  load-job:
    runs-on: ubuntu-latest
    needs: transform-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run load.py
        run: python load.py
